all:
	g++ Rocket.cpp Logs.cpp Launch.cpp -o ./build/Launch
clean:
	rm *.o ./build/


run:
	./build/Launch
run_diagnostics:
	./build/Launch diagnostics rocket_one
run_launch:
	./build/Launch launch rocket one
